version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.3-jessie-node
        environment:
          BUNDLE_PATH: vendor/bundle
    steps:
      - checkout
      - restore_cache:
          keys:
            - ruby-gems-v001-{{ checksum "www/Gemfile.lock" }}
      - restore_cache:
          keys:
            - node-modules-v001-{{ checksum "www/package-lock.json" }}
      - run:
          name: Install Dependencies
          command: ./bin/deploy/install.sh
      - save_cache:
          key: ruby-gems-v001-{{ checksum "www/Gemfile.lock" }}
          paths:
            - vendor/bundle
      - save_cache:
          key: node-modules-v001-{{ checksum "www/package-lock.json" }}
          paths:
            - www/node_modules
      - run:
          name: Compile
          working_directory: www
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              npx gulp --production
            else
              npx gulp
            fi
      - run:
          name: Test
          command: ./bin/deploy/test.sh
      - deploy:
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              ./bin/deploy/deploy.sh
            fi
