# Site data
title: Josh Cummings | Front-End Developer
description: Hi, my name is Josh Cummings and I'm a front-end developer from San Diego, CA.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://joshcummingsdesign.com" # the base hostname & protocol for your site
blog-link: "https://medium.com/@joshcummingsdesign"
work-link: "https://dribbble.com/joshcummingsdesign"
twitter: jcummingsdesign
linkedin: joshcummingsdesign
instagram: jcummingsdesign
codepen: joshcummingsdesign
dribbble: joshcummingsdesign
github: joshcummingsdesign

# Build settings
source: "."
destination: _site
layouts_dir: src/templates/_layouts
includes_dir: src/templates/_includes
data_dir: src/templates/_data
exclude:
  - _site
  - html
  - node_modules
  - vendor
  - gulp
  - src
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - package.json
  - package-lock.json
include: ['.htaccess']

# Markdown settings
markdown: kramdown
kramdown:
  auto_ids: false

# Server settings
host: 0.0.0.0
