/**
 * Renders the posts HTML.
 *
 * @param {object} posts {title, date, link, image}
 * @return {string}
 */
const renderPosts = (posts) => {
  return posts.reduce((html, post, i) => {
    html += `
      <!-- Generated by medium.js -->
      <div class="blog-archive-post ${i % 3 === 0 ? 'col-sm-12' : 'col-sm-6'}">
        <a class="blog-archive-link super-link" href="${post.link}">
          <div class="blog-archive-img-overlay"></div>
          <article class="blog-archive-box">
            <div class="blog-background-image" style="background-image: url(${post.image});"></div>
            <div class="blog-archive-text">
              <h3>${post.title}</h3>
              <p>${post.date}</p>
            </div>
            <p class="more-posts-btn">Read More</p>
          </article>
        </a>
      </div>
      <!-- End medium.js -->
   `;
    return html;
  }, '');
};

module.exports = {
  renderPosts,
};
